freescout-help-desk/freescout

app/Mailbox.php, composer.json, database/migrations/2018_11_13_143000_encrypt_mailbox_password.php
=> Crypt password used for email fetching

public/css/style.css
fix problem: cannot click checkboxes in conversation list on mobile screen size
=> fix: make conversations checkbox clickable for mobile version

resources/views/auth/login.blade.php, resources/views/auth/passwords/email.blade.php, resources/views/auth/passwords/reset.blade.php, resources/views/auth/register.blade.php, resources/views/conversations/conversations_table.blade.php, resources/views/conversations/partials/bulk_actions.blade.php, resources/views/conversations/partials/prev_convs_short.blade.php, resources/views/conversations/view.blade.php, resources/views/emails/user/password_changed.blade.php, resources/views/emails/user/password_changed_text.blade.php, resources/views/js/vars.blade.php, resources/views/mailboxes/auto_reply.blade.php, resources/views/mailboxes/connection.blade.php, resources/views/mailboxes/connection_incoming.blade.php, resources/views/settings/alerts.blade.php, resources/views/settings/general.blade.php, resources/views/users/notifications.blade.php, resources/views/users/password.blade.php, resources/views/users/profile.blade.php
Fix spelling and grammar
Remove references to Help Scout
Standardise spellings (for example E-Mail, E-mail and Email).
Remove some white space (automatic editor setting on save)
=> Improve text

app/Conversation.php, app/Misc/Mail.php
You can now use the following variables in your signature:
```
{%user.fullName%}
{%user.firstName%}
{%user.lastName%}
```
Would be awesome if this could be merged and released ASAP because Help Scout is killing our account after their bait & switch and we'd like to move to FreeScout!
Thanks for making this amazing free alternative!
=> Adds user related variables to signature (Closes #146)

app/Console/Commands/FetchEmails.php
Small improvement to bounce detection. Quick & Dirty fix to detect AWS bounces and Exim bounces
=> Bounce detection improvement

resources/views/mailboxes/update.blade.php
Call hook in mailbox update page to allow module developers customize the mailbox update page
=> Call hook in mailbox update page

app/Console/Commands/FetchEmails.php
As per #184 here we add a new hook to block thread creation (needed by module developers)
=> Add "fetch_emails.should_save_thread" hook

app/Console/Commands/FetchMonitor.php, app/Console/Kernel.php, app/Http/Controllers/SettingsController.php, app/Misc/Mail.php, config/app.php, resources/views/settings/emails.blade.php
Some email services have limits for connections, and make IMAP connection every minute is wrong.
=> fetch mail schedule setting

app/Misc/Helper.php, app/Thread.php, resources/views/conversations/view.blade.php
The code used was released under the public domain by GitHub user jasny
https://gist.github.com/jasny/2000705
Close #341
=> Detect links inside the E-Mail and convert them to html links

app/Http/Controllers/MailboxesController.php, app/Http/Controllers/SecureController.php, public/js/laroute.js, public/js/main.js, resources/views/conversations/view.blade.php, routes/web.php
Hi, changed it to work as you described, please check it! Regards
=> Feature request: adding images to mailbox signature #366

app/Mail/UserInvite.php
=> Use getCompanyName() wrapper for fallback value

app/Jobs/SendReplyToCustomer.php, app/Mailbox.php, database/migrations/2020_04_16_122803_add_reply_folder_column_to_mailboxes_table.php, resources/views/mailboxes/connection.blade.php
=> Save reply email to mailbox

database/migrations/2018_07_09_053559_create_customers_table.php, database/migrations/2018_07_12_003318_create_threads_table.php, database/migrations/2018_08_06_114901_create_send_logs_table.php
Updates the Migrations to support Postgres. 
Fixes #510 and #472
=> Postgres Support

app/Http/Controllers/ConversationsController.php, resources/views/conversations/partials/bulk_actions.blade.php
Fixes #648
Also I add "anyone" option to bulk action. I think that it was ommited by mistake.
=> Fixes 648 "Hide from Assign list" in Bulk Actions

app/Conversation.php, app/Http/Controllers/ConversationsController.php, app/Jobs/SendReplyToCustomer.php, database/migrations/2020_06_26_080258_conversations_add_history_setting.php, resources/views/conversations/partials/settings_modal.blade.php, resources/views/conversations/view.blade.php
For now this only includes history settings (an override to the global setting per conversation)
This is a new attempt from a fresh master fork.
=> Added conversation settings

app/Console/Commands/FetchEmails.php
In response to #735 with cleaner code than the example.
I have not yet tested this.
=> Convert subject to UTF-8 encoding

resources/views/mailboxes/permissions.blade.php
#785 
Added overflow-x: auto to permissions manager to make it scrollable on mobile
=> make permissions manager scrollable on mobile screens

resources/views/conversations/partials/thread.blade.php, resources/views/conversations/partials/thread_attachments.blade.php
Hi,
this pull add a download link for directly download an attachment
=> Add download button to attachment

app/Http/Controllers/ConversationsController.php
=> set "to" in new conversation with url parameter

app/Http/Controllers/ConversationsController.php
=> set closed_at if conversation is closed after reply

app/Console/Commands/FetchEmails.php
=> fetch emails hook unseen

app/Console/Commands/FetchEmails.php, resources/views/emails/customer/auto_reply_text.blade.php, resources/views/emails/customer/reply_fancy_text.blade.php, resources/views/emails/user/notification.blade.php, resources/views/emails/user/notification_text.blade.php
This fixes the problem of unapplied custom reply separator according to the mailbox setting.
Warning: I have not tested this with the checkbox disabled yet due to lack of time. Maybe someone else can do this and report back here?
Closes #730
=> Fixed custom reply separator

resources/views/conversations/conversations_table.blade.php
Issue: #1145 
Please let me know if I need to change something :)
=> Hook to show followers in the mailbox dashboard

app/Mailbox.php, database/migrations/2021_05_21_090000_encrypt_mailbox_out_password.php
Suggestion to fix #328
To replace this pull request #1226
=> Encrypt out_password

resources/views/conversations/partials/thread.blade.php, resources/views/conversations/view.blade.php, resources/views/layouts/app.blade.php, resources/views/mailboxes/sidebar_menu_view.blade.php, resources/views/secure/dashboard.blade.php
approach:
```sh
git checkout -b flower --track origin/master
git reset --hard 9c1ac14bf1595d87bb09d657fafed34123482e52 
git cherry-pick a82e5d6285fecbe49e4654b2c8035415a9f1b0eb...2eecaf3491d87028eac62c1221a6f2f6675b688c
// fix
git cherry-pick --continue
git push --force git@github.com:fulldecent/freescout.git flower:patch-4
```
=> Add button role for conversation actions, try 2

app/Http/Controllers/PublicController.php
Fixes #1252 "Missing format specifier at end of string" in sprintf due to mismatched number of % and format specifiers.
=> Fixes #1252

app/Observers/ThreadObserver.php
This caused all kinds of weird behaviours, where one of them was #1574. This fixes it.
=> Fix Workflow Email to Customer action

routes/web.php
#1668 
This can be solution of this issue
if ```APP_DASHBOARD_PATH``` is empty it will redirect to ```/``` only
=> Freescout 1.7.30 redirecting to root

app/Console/Commands/FetchEmails.php
This fixes a loop that is caused by moving a conversation to
another mailbox. In that case the old mailbox was still visible
as a CC when replying on the moved converstaion. This CC would
result in a new converstation being created.
=> fix: do not add mailbox emails itself to CC in new conversation

app/Mailbox.php, resources/views/conversations/partials/thread.blade.php
- A filter for the outgoing mail From name
- Filters to add information to the thread recipients
=> Multiple filters

app/Misc/Mail.php, public/js/main.js, resources/views/js/vars.blade.php
A corresponding Feature-Request exists here: <https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f>
=> Add customer.company variable to templating

public/css/style-rtl.css, resources/lang/fa.json
Keep in mind that pull requests should be sent to the `master` branch! See https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#github-workflow
Now you can delete this text and type the description of your pull request...
=> Make some modifications in RTL style to fix view issues.

app/Customer.php, resources/views/layouts/app.blade.php, resources/views/mailboxes/sidebar_menu.blade.php, resources/views/mailboxes/sidebar_menu_view.blade.php, resources/views/mailboxes/update.blade.php, resources/views/secure/dashboard.blade.php
=> Changes for mailbox icons and customer avatars modules

resources/lang/fr.json, resources/views/customers/partials/edit_form.blade.php, resources/views/customers/profile_snippet.blade.php
Two commits to enhance the customer form.
The first is to use navigator build-in helper for emails, phone and url fields.
The second is to edit and show the phone type of phone numbers (home, mobile, fax, ...). This informations was already in the database but was not usable.
=> Enhance of customer form

app/Console/Commands/FetchEmails.php, app/Mailbox.php, resources/views/conversations/editor_bottom_toolbar.blade.php, resources/views/conversations/view.blade.php, resources/views/mailboxes/update.blade.php
Additional action per issue #2167
=> New action before_prev_convs per issue #2167 + An ability to keep current status and assignee per issue #2180

resources/lang/cs.json, resources/lang/de.json, resources/lang/es.json, resources/lang/fa.json, resources/lang/fr.json, resources/lang/it.json, resources/lang/ja.json, resources/lang/ko.json, resources/lang/nl.json, resources/lang/pl.json, resources/lang/pt-BR.json, resources/lang/pt-PT.json, resources/lang/ru.json, resources/lang/sk.json, resources/views/settings/general.blade.php
=> Fix grammar application better

app/Conversation.php, app/Http/Controllers/ConversationsController.php
This will allow searching by customer first and last name to find threads or customers. It also ignores cases on more things.
=> Search improvments

resources/views/layouts/app.blade.php
Add a @filter to allow changing of the theme-color <meta> tag.
=> Add theme-color meta tag @filter

resources/views/layouts/app.blade.php
Add @action to allow customisation *after* the mailbox name in the mailbox menu.
e.g. add unassigned conversation count.
=> Add `menu.mailbox.after_name` @action

app/Observers/CustomerObserver.php
This commit adds a new method to the CustomerObserver class that triggers an event when a customer is being deleted.
=> feat: add customer deleting event

.github/workflows/test.yml
This is a first step for setting up continuous integration.
=> Create continuous integration test

app/Console/Commands/FetchEmails.php
I found it useful to change the destination mailbox to the message based on the folder it was retrieved.
=> Add filter `fetch_emails.mailbox_to_save_message`

public/css/style.css
fixes https://github.com/freescout-helpdesk/freescout/issues/3693
=> improve contrast on on unread notifications

.github/workflows/lint-php.yml
This updates testing to use the current PHP version for linting
=> Use latest PHP version for linting

app/Console/Commands/FetchEmails.php
Fixes https://github.com/freescout-helpdesk/freescout/issues/4020 
It iterates all the possibilities of reply IDs and using the first we found in our freescout threads, following the order: In-Reply-To, References (by order), special FS marker. In most cases it will work as always (getting the In-Reply-To at the first attempt), but if not, it will try the other possibilites.
=> Find prev_thead iteratively looking in-reply-to and references

resources/lang/es.json
The translation says the opposite than the original intention
=> Fix bad translation

app/Mail/ReplyToCustomer.php, app/Mail/UserNotification.php
Requesting to add several filters to enable customisation of email reply and user notification templates. This would enable a broad range of customisations through modules.
=> Added filters allowing module customisation of email reply and user notification templates

app/Conversation.php, app/Http/Controllers/ConversationsController.php, app/Http/Controllers/CustomersController.php
See related https://github.com/freescout-help-desk/freescout/issues/4521
=> feat: add searching by user fullname for conversations and customers

resources/views/partials/timezone_options.blade.php
This is a fix for issue #4675  relating to timezone template partials.
=> Timezone fix for Kolkata

app/Http/Controllers/UsersController.php, resources/views/users/partials/web_notifications.blade.php
I've changed my modifications from last week to actions and filters so the desired functionality can be built in a custom module.
=> Added actions and filters

resources/views/customers/profile_tabs.blade.php
Adds a new actions, `customers.profile_tabs.append`, for easy appending of new tabs in the Customer's profile
=> feat: add action to append profile tab

app/Console/Kernel.php
There's an option to set the frequency of fetch to 2 & 3 minutes but that feature is not functional. This PR adds backend support for 2 & 3 minute fetch intervals.
=> Add missing schedule options for fetch command

resources/views/users/partials/web_notifications.blade.php
Added a filter on the profile picture in a web notification
=> feat: filter for web_notification person
