freescout-help-desk/freescout

config/purifier.php

without table tags many emails showed wrongly formatted.

show table tags(table,tr,td) in conversation email body

---

app/Attachment.php

Fix for #327 
Only alphanumeric and dashes allowed in file names. This will ensure the browser can load all file urls without adverse interactions.

Slugified attachment file names

---

app/Misc/Mail.php
app/User.php
public/js/main.js
resources/views/js/vars.blade.php

As proposed in #281 this PR will replace the following fields in the signature with the corresponding values (5604cf1356f7de98283aadba11286e5944a46ac4):
- `mailbox.fromName` => The from name of the mailbox
- `user.phone` => The phone number of a user
- `user.email` => A users E-Mail set in the preferences
- `user.jobTitle` => A users job title
It is also visible in the UI (831ca7c3cbc939fe589bee1352307abaf7803d3a).
Close #281

More fields in signature

---

app/Http/Controllers/ConversationsController.php

As suggested in #338, this PR does not display mails marked as spam in the previous Conversations tab. I decided to hide them instead of adding a label because it wouldn't hide the irrelevant content. I want to see previous conversations with current information, and the spam label is closest to hiding an email from that list.
Close #338

Do not show spam mails in previous conversations

---

app/Misc/Mail.php
app/User.php
public/js/main.js
resources/views/js/vars.blade.php

As discussed [here](https://github.com/freescout-helpdesk/freescout/issues/281#issuecomment-540992628), this PR adds a variabel `user.photoUrl` for use in the signature.
Finally close #281

Photo URL as Variable in signature

---

overrides/Webklex/IMAP/Message.php

The problem is in webklex/laravel-imap (old version) and its override, applied to the override the changes proposed in this other pr: https://github.com/Webklex/laravel-imap/pull/175/commits/884bde831e10eb4227d10f1e79b922ce62c3ad70

Spaces in some conversation titles are replaced by underscores #420

---

resources/views/layouts/app.blade.php

I'm not so sure if I'm right with this. I'll explain, I'm doing a custom module and wanted to add menu items either in the main menu or inside admin menu: 
So I added two new filter positions to the blade template

Adding new filters to allow hooking menu items from third party modules

---

public/js/main.js

This fixes freescout-helpdesk/freescout#487 with copy+pasting a string containing multiple emailaddresses separated by any of the allowed tokens. Before this patch, all emailaddresses became a single tag.
Before:
After:
I'm aware that the last item is not correctly tokenized. This is due to https://github.com/select2/select2/issues/5076. I'm looking at applying the workaround as well, but it did not immediately work.

Fix tokenization of multiple emails on copy+paste of multiple emails

---

app/User.php

In relative dates on a Dutch system the word 'minute' is written as 'minuten'. When shortening this word to 'min' the trailing 'n' remains. This fix makes sure the trailing 'n' is also removed.
Current: `49 minn geleden`
With fix: `49 min geleden`

Remove trailing n from relative date minutes for Dutch systems

---

app/Console/Commands/CreateUser.php

This allows for automation of initial admin account creation together with the already supported `--no-interaction` option.
All options are optional and if not provided will be asked for.
This requirement came up while I was packaging freescout for Cloudron due to popular request.

Add commandline arguments to freescout:create-user

---

.editorconfig

Works great in many editors and on Github

Add .editorconfig for consistent whitespace

---

app/Jobs/SendNotificationToUsers.php
app/Jobs/SendReplyToCustomer.php
resources/views/settings/general.blade.php

This adds a third option `Include the last message` to Settings > Conversation history (#447)
In my tests the notification mails look the same as the current 'Send full conversation history' with only the new reply and the one before that included.
I wasn't sure if the code should be added before or after the `\Eventy::filter()`, but it doesn't seem to matter.
~Edit: the staff notifications are still the full list, I don't know where that can be altered.~

Add option to include the last message in notifications

---

app/Http/Controllers/SettingsController.php
app/Jobs/SendNotificationToUsers.php
config/app.php
resources/views/settings/general.blade.php

In follow up to #535, this adds a new section Manage > Settings > General > **Emails to Users** with the same **Conversation History** drop menu and its default setting as in _Emails to Customers_.
This allows to configure the notifications for better GDPR compliance, by setting the history to 'none' for users and 'last' for the customer for their convenience. This way there are less copies of PII amongst staff, reducing the risk of data leaks.
Additionally I added a missing comment I forgot about in my other PR #535.

Add setting for conversation history in user notifications

---

resources/views/emails/user/notification.blade.php

Mac mail (at least) removes elements that are set to display none when you're replying. Because the {#FS:****#} was in an hidden div it was removed, and freescout was not able anymore to relate the reply to the original conversation. Simply removing the display none fixes that.

Fix for reply on notification e-mail not assigned to original conversion

---

app/Misc/Helper.php

I ran into an weird issue that it tried to use `$_SERVER['ORIG_SCRIPT_NAME']` while it wasn't defined. Therefore these changes check if this array key even exists before using it.

Check if ORIG_SCRIPT_NAME exists before using it

---

database/factories/CustomerFactory.php

I have wrapped the code in json_encode as I can see from the migration file comment that this database field is json.
Issue: https://github.com/freescout-helpdesk/freescout/issues/706#issue-684149054
Previous output:
```php
array:1 [
0 => array:2 [
"value" => "290-258-2556 x0587"
"type" => 1
]
]
```
New output: 
```php
"[{"value":"(519) 427-5834","type":1}]"
```
Manual test:

Customer factory now generates json for 'phones' field.

---

public/css/style.css

_(this is a redo on master branch)_
This CSS fix for issue #612 makes sure that large images are limited to a maximum width of 100% of its parent `<p>` tag.
Because all attached images are already available for download at the bottom of the message, the image does not need to be linked.
I have tested this on the latest stable versions of Safari, Firefox and Edge on macOS and Safari & Firefox on iOS.

Rescale large images for readability

---

app/Http/Controllers/MailboxesController.php
app/Mailbox.php
app/Policies/MailboxPolicy.php
app/Policies/UserPolicy.php
app/User.php
database/migrations/2020_09_18_123314_add_access_column_to_mailbox_user_table.php
resources/views/mailboxes/email_signature.blade.php
resources/views/mailboxes/permissions.blade.php
resources/views/mailboxes/settings_menu.blade.php
resources/views/mailboxes/update.blade.php
routes/web.php

Updates permissions page to edit per user permissions as defined.
Permissions stored in mailbox_user.access and defined in Mailbox ($USER_ACCESS_PERMISSIONS)
Hides pages and options without permission on templates:
- delete button
- mailbox address and name only editable by admin
- settings_menu
Added policy definitions to check permissions on each save page.
Moves email signature to own edit page (similar to Auto-Reply) to keep managers from needing to see breakable settings.

Issue 490: Mailbox Managers and per user management permissions

---

app/Http/Controllers/ConversationsController.php

Fixes `prefill_to` introduced in #940 and improved in 3446abd.
It must be an array with keys in order to set correctly.
https://github.com/freescout-helpdesk/freescout/blob/920690e50454af3d89454ea406c344c6b524b390/resources/views/conversations/create.blade.php#L141-L143

Fix prefill_to

---

resources/views/customers/profile_snippet.blade.php

We noticed the user email link in sidebar goes nowhere:
It only had `href="#"` on it, so we fixed that to go to:
```
{{ $mailbox->url() }}/new-ticket?to={{ urlencode($email->email) }}
```
That actually does give you the new ticket screen with the email address pre-filled.

Fix email customer link

---

composer.json

Update fzaninotto/faker to fix issue due to changes with implode() in PHP >= 7.4 (see fzaninotto/faker#1748). Otherwise, DB seeding is broken on >= PHP 7.4:

Update fzaninotto/faker to fix PHP >= 7.4 compatibility

---

app/Http/Controllers/ConversationsController.php

When multiple agents were viewing an email, the following error was seen:
usort(): Returning bool from comparison function is deprecated, return
an integer less than, equal to, or greater than zero at
/www/html/app/Http/Controllers/ConversationsController.php:252
Fix as is from comment by freescout-helpdesk to #1395

Fix page generation error with multiple agents

---

app/Http/Controllers/ModulesController.php

Add support for module.json 'img' attribute. Use this to set a path to the image for your custom module icon/logo.

Add support to get module image from modules.json

---

public/js/main.js

Change aria-hidden attribute to aria-modal attribute to make modal dialogs accessible for screen readers

Improve accessibility of modal dialogs (#1150)

---

app/Console/Commands/FetchEmails.php
app/Http/Controllers/MailboxesController.php
app/Mailbox.php
public/js/main.js
resources/views/mailboxes/connection_incoming.blade.php

This allows us to create custom importers for e-mail. It will use the FetchEmails class to add the e-mails by "simulating" the Message and Attachment classes. An example for Postal, [here](https://github.com/Wouter0100/freescout-postal/).
It would also be possible to use this for example for AWS SES Incoming emails and other e-mail providers providing incoming e-mail abilities.
No behaviour changed by default.
https://user-images.githubusercontent.com/864520/146613993-d801d2d6-bb89-4205-912e-f6cc17c4e205.mp4

Added hooks for custom fetch email providers

---

app/Misc/Helper.php
app/Thread.php

Currently, when using `$thread->getBodyAsText()` as is done in the Twitter module, [there is no way](https://github.com/freescout-helpdesk/freescout/blob/dist/app/Thread.php#L298) to [configure the underlying library](https://github.com/freescout-helpdesk/freescout/blob/f4924c3140439365d62802d1ee6697ed3bea59d2/app/Misc/Helper.php#L992) of `Html2Text`. This ability is important if you want to remove word wrapping. [The default wrapping max length](https://github.com/freescout-helpdesk/freescout/blob/f4924c3140439365d62802d1ee6697ed3bea59d2/vendor/html2text/html2text/src/Html2Text.php#L217-L219) in `Html2Text` is 70. This looks horrible in a Twitter DM when newlines are added every 70 characters. This PR adds the ability to pass a config array to `getBodyAsText` that [will make it down to …

Add ability to pass config to Html2Text

---

app/Http/Controllers/ConversationsController.php
app/Http/Controllers/MailboxesController.php
public/js/main.js
resources/views/conversations/conversations_table.blade.php
resources/views/mailboxes/view.blade.php

The sorting can be done by clicking on the column names while showing correct sorting arrow next to the name when necessary. 
By default it it's using the created_at ascending order sorting.

Added Conversations sorting by subject, Number, Creation Date in Mailbox view page

---

resources/views/auth/login.blade.php
resources/views/auth/passwords/email.blade.php
resources/views/auth/passwords/reset.blade.php
resources/views/auth/register.blade.php

This Pull Request adds "autocomplete"-tags to all auth views of freescout to optimize its behavior in conjunction with a password manager.
It would be great if this could also be added to the 2FA/OTP Module
(in Resources/views/auth.blade.php:34 add autocomplete="one-time-code"
For reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

Add autocomplete Tags to Auth Views

---

app/User.php

Added a check for empty strings passed to json_decode. This was throwing an error "json_decode(): Passing null to parameter #1 ($json) of type string is deprecated" when logged in as a standard user on PHP 8.1.

add empty string check

---

app/Jobs/SendAutoReply.php
app/Jobs/SendEmailReplyError.php
app/Jobs/SendNotificationToUsers.php
app/Jobs/SendReplyToCustomer.php
app/Mailbox.php
app/Misc/Mail.php

A customer would like an (outgoing) alias module. For that to work, the outgoing address should be filtered.
This PR adds the necessary filters for that.
I tried to keep it as clean as possible.

Add filters to be able to filter SMTP settings when sending a mail

---

app/Jobs/SendNotificationToUsers.php

I wish to add a header to outgoing mail (see: https://github.com/freescout-helpdesk/freescout/pull/1866). I was told to do it as an external module.
This PR adds the necessary filter to allow that.

Add filter allowing customisation of outgoing headers

---

resources/views/mailboxes/partials/folders.blade.php
resources/views/secure/dashboard.blade.php

This pull request is:
Helpful when cards need to have different stylings or the global mailbox needs to be styled differently than normal mailboxes.
Example:
Allowing the icon name as a class selector is required to change the order of the folders in the sidebar.
It is also useful when adding css-only diviers.
Can be used to hide empty folders from the sidebar. Especially useful when used together with the icon class name.
Example:
These changes are not vital, but create more flexibility when styling FreeScout using the official [Customization module](https://freescout.net/module/customization/).
Thanks!

Small optimizations to better style dashboard cards and sidebar folders

---

app/Console/Commands/FetchEmails.php

Hello,
This is a fix to a pop3 mail account. As the fetching is OK (logs), but no ticket created.
I found that no folder was processed if not in IMAP protocols.
Fix #2092

Default folder INBOX

---

resources/views/emails/customer/reply_fancy.blade.php

As per #2111  - minor change to email template for customer reply so email tracking works on some server configs

Fix for #2111 removed trailing slash from tracking pixel route

---

app/Http/Controllers/ConversationsController.php
public/js/main.js
resources/views/conversations/partials/thread.blade.php
resources/views/conversations/view.blade.php

As discussed in #2141, changes to preserve the x_embed param while conversations are worked on in an iframe (e.g. with the kanban module):
- Fixes some routes in views to preserve existing query params (this fixes actions like view outgoing emails in conversation modal view)
- Checks for x_embed in current URL and appends to redirect URL - this preserves the modal display, which excludes the top nav menu, while working within the iframe.
- Changes to conversation controller to stay on same page if iframe and not redirect to conversation list (as conversation list is available in the kanban master window).

Changes for #2141 - fixes for UI issues for conversation display in kanban

---

public/js/main.js

The [Mentions Module](https://freescout.net/module/mentions/) is using the Summernote `hint` feature by assigning an object to `options.hint`:
```js
/Modules/Mentions/Public/js/module.js:8
options.hint = {...}
```
This results in other modules not being able to use their own hints without risking being overwritten by the Mentions Module.
Luckily summernote supports multiple hints by using an array instead of an object.
This pull request is initializing `options.hint` as an empty array - in order to populate it within modules.
Accepting this pull request requires the following changes to the Mentions Module's javascript:
```js
/Modules/Mentions/Public/js/module.js:8
options.hint.push({...})
```

Allowing multiple summernote hints

---

resources/views/conversations/conversations_table.blade.php

Before
After
---
Requesting testing by others to confirm this does not mess up other uses of conversation view, specifically with paging.

Make conversation history table wider in customer profile, Fix #61

---

app/Conversation.php
resources/views/conversations/search.blade.php

Fixes https://github.com/freescout-helpdesk/freescout/issues/2367
Adds a new dropdown for the "Unassigned" user to the "Assigned" filter like so:
Result:

Search for tickets assigned to "Anyone" - fixes #2367

---

app/Http/Controllers/ConversationsController.php
resources/views/conversations/partials/thread.blade.php
routes/web.php

Hi there,
We sometimes see that customers are hijacking a conversation by switching to a different issue while replying to the previous issue. It ends up in freescout, ideally we want to disconnect that message from the conversation, so we keep this new issue separated from the old.
This feature adds a 'clone conversation' to the context menu of messages and makes a brand new conversation based on that message. Somewhat similar to 'new conversation'. The original conversations remains the same, because it most likely also references the issue in that thread, so we don't want to remove it there.
I hope I did everything right, my first pull request, so please do not scream at me.
Tom

Add possibility to clone a conversation.

---

resources/views/layouts/app.blade.php

If there's only one mailbox, the existing `menu.mailbox.before_name` and `menu.mailbox.after_name` action's didn't apply.
This PR uses the same actions when there's a single mailbox.

Add menu.mailbox.before_name and after_name actions for only one mailbox

---

app/Folder.php
app/Jobs/UpdateFolderCounters.php

When you have a lot of mailboxes, a lot of users and you use tags and the custom folders plugin excessively, every action becomes extremely slow (on serious dedicated hardware, sending a mail took 20s, deleting the same), because each action triggers a updateCounters for each folder. 
In this PR, the updateCounters function is moved to a job. When you have an extreme amount of folders, it will take a few seconds before the counters update, but everything else is way faster. When you have 1 mailbox with some folders, you won't notice a difference.
I also built a small part that checks if the job is already queued. If it is, it won't be added again. So removing 10 mails won't add all folders 10 times to the queue. Feel free to make this optional via the settings or something (you could use …

Update folders counters in background

---

app/Conversation.php

If a user is "following" a conversation and the conversation is then assigned to them they no longer need to follow it.
PR for issue #2994

Unfollow followed conversation when re/assigned

---

app/Observers/FollowerObserver.php

This PR fixes the "Undefined variable: attachment" error in the FollowerObserver class.

Fixed undefined variable bug in the FollowerObserver

---

overrides/barryvdh/laravel-translation-manager/src/Manager.php

set $locale before preg_match.because if former foreach ended contine condition.  module translation file would be never importerd.

Fix module translation file never imported under certain condition.

---

tools/update.sh

It is preferable to run the custom `post_update.sh` at the very end, because module updates may influence things you want to alleviate with a post update script.

Post update after modules

---

config/database.php

Required for PaaS DB servers that require SSL.

Allow .PEM insertion for MySQL connections

---

app/Console/Commands/ModuleUpdate.php
app/Http/Controllers/ModulesController.php
app/Module.php
resources/views/modules/partials/module_card.blade.php

This PR adds the functionality to check the version of third party modules and update them when required.
To make it work, the following lines should be added to the modules module.json:
```json
{
...
"latestVersionUrl": "[link to a text file containing the latest version number]",
"latestVersionZipUrl": "[link to a zip file containing the latest module in a zip file]"
}
```
This PR also adds the author's name to the module card.

Allowing updates for third party modules

---

app/Misc/Helper.php

Makes the params parameter in setGuzzleDefaultOptions optional. This fixes the bug in ModulesController:162 where the function is called without it and producing a fatal error. 
I made the change in ModulesController, so I could have changed it there. But I think it's better to make $params optional, since it actually is optional.

fix: optional params in setGuzzleDefaultOptions

---

app/Console/Commands/FetchEmails.php

This change introduces an optional command option `mailboxes`, which can be used to limit fetching messages to particular mailbox ids.
The following example fetches all messages of the last 500 days for the specific mailboxes 5 and 7 only. By omitting the new `mailboxes` option, any message of any mailbox would have been fetched.
```
php artisan freescout:fetch-emails --mailboxes=5,7 --unseen=0 --days=500
```

Allow limiting command freescout:fetch-emails to specific mailboxes

---

app/Conversation.php
app/Http/Controllers/ConversationsController.php

This PR introduces an event for when the subject of a conversation is changed. It works in a similar fashion to when e.g. the status of a conversation is modified.
Closes #4127 (my original issue).

Add `Conversation->changeSubject()` and `conversation.subject_changed` action

---

config/database.php

This change adds the environment variable `DB_ATTR_PERSISTENT` to request a persistent db connection instead of creating a new connection for every request. This can be useful if opening a database connection is slow, e.g. if the db is on a different host and TLS is enabled.
Persistent connection are supported by MySQL and PostgreSQL PDO driver, but I only tested PostgreSQL and had no issues so far.
The sqlsrv driver does not support it, therefore I left it out: https://github.com/Microsoft/msphpsql/issues/65
The used doctrine version does not support persistent connections, but laravel 5 implemented a workaround:
https://github.com/laravel/framework/pull/16702
Reference:
https://www.php.net/manual/en/pdo.constants.php#pdo.constants.attr-persistent

Allow to enable persistent connections for MySQL and PostgreSQL

---

public/js/summernote/summernote.js

Fixes https://github.com/freescout-help-desk/freescout/issues/3811
In earlier verisons of freescout, not all 'p' where replaced with 'div' so the insertParagraph method didn't work. But now it's well replaced (I checked it and marked every change with a comment), so it's safe to use insertParagraph again.
So this PR just adds the comments, remove the forced shift in enter, and puts again the keymap.
With this PR now it's easy to go out from code/citation blocks (just press enter, if you wanna a new line inside you have to press shift+enter), keeping divs as a separator.
It also keep other expected behaviours like pressing shift+enter in a list to add a subline.

Use keyMap Enter->insertParagraph in editor as it insert divs

---

app/Mail/UserNotification.php

Added `$this->conversation` parameter to allow the Ticket Module to override the email subject.
@freescout-help-desk  Can the Ticket Module hooks function be updated to include this event:
```
\Eventy::addFilter('email.user_notification.subject', function($subject, $conversation) {
$prefix = config('ticketnumber.prefix');
$suffix = config('ticketnumber.suffix');
return $prefix.$conversation->number.$suffix.$conversation->subject;
}, 20, 2);
```

Update email.user_notification.subject Eventy filter
